'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Register
    
    '''<summary>
    '''userNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''userNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''userNameRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''PK_ViolationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PK_ViolationLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''passwdLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwdLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''passwdTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwdTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''passwdRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwdRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''confirmPasswdLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmPasswdLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''confirmPasswdTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmPasswdTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''passwdNotMatchedLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwdNotMatchedLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''emailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''emailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''emailRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''emailRegularExpressionValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''questLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents questLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''questionDropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents questionDropDownList1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ansLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ansLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ansTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ansTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ansRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ansRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''createButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createButton As Global.System.Web.UI.WebControls.Button
End Class
