'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reservation
    
    '''<summary>
    '''GuestNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GuestNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GuestNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GuestNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''dbErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dbErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''roomTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents roomTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''roomTypeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents roomTypeDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''roomEntityDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents roomEntityDataSource As Global.System.Web.UI.WebControls.EntityDataSource
    
    '''<summary>
    '''arrivingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arrivingLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DepartureLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepartureLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''arrivalCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arrivalCalendar As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''departureCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departureCalendar As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''arrivingErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arrivingErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DepartureErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepartureErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''creditCardTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents creditCardTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''creditCardTypeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents creditCardTypeDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reservationButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reservationButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''creditCardLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents creditCardLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''creditCardTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents creditCardTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''clearButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearButton As Global.System.Web.UI.WebControls.Button
End Class
