'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CottagesEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CottagesEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Beds() As DbSet(Of Bed)
    Public Property Guests() As DbSet(Of Guest)
    Public Property Reservations() As DbSet(Of Reservation)
    Public Property Rooms() As DbSet(Of Room)
    Public Property States() As DbSet(Of State)

End Class
